# Generated by Django 2.1.4 on 2019-01-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questanswers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
